### ISSUE TITLE
Cura source

### ISSUE THREAD

**Issue by BagelOrb** [MalyanSystem/GPX#1]
Where is the source code for the Malyan version of Cura?

**Comment by yongzong** [comment]
There is no Malyan version Cura. They only added their printer profile.

**Comment by BagelOrb** [comment]
They also added a Cura plugin for x3g support. 

Where can I find the source for this plugin and for the printer profile?

**Comment by nallath** [comment]
Due to AGPL licence of Cura, you would need to also release the source code of the x3g support plugin.

**Comment by yongzong** [comment]
Please check: https://github.com/MalyanSystem/Cura_plugins

The plugins is simply a wrapper to call GPX.exe

2016-01-12 17:45 GMT+08:00 Jaime van Kessel notifications@github.com:

**Comment by nallath** [comment]
Cool, thanks :)
